server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_SCHEMA_PROD}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: fryday-prod

logging:
  file:
    name: /home/ubuntu/logs/prod/application.log
  logback:
    rollingpolicy:
      max-history: 7